name: htx
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas==2.0.3
  - fastapi==0.104.1
  - uvicorn==0.20.0
  - transformers==4.31.0
  - librosa==0.9.2
  - python-multipart==0.0.6
  - elasticsearch==8.11.0
  - python-dotenv==1.0.0
  - pip:
    - torchaudio==2.1.1