version: '2.2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch1
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch2
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:3000"
      - http.cors.allow-methods=GET, POST, PUT, DELETE, OPTIONS
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,x-elastic-client-meta
      - http.cors.allow-credentials=true
    networks:
      - esnet
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'You Know, for Search'"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  elasticsearch2:
    depends_on:
      - elasticsearch1
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch2
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    environment:
      - node.name=elasticsearch2
      - cluster.name=es-cluster
      - discovery.seed_hosts=elasticsearch1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - cluster.initial_master_nodes=elasticsearch1,elasticsearch2
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:3000"
      - http.cors.allow-methods=GET, POST, PUT, DELETE, OPTIONS
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,x-elastic-client-meta
      - http.cors.allow-credentials=true
    networks:
      - esnet
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200 | grep -q 'You Know, for Search'"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  esnet:
    driver: bridge

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
